ALTER TABLE IF EXISTS "product" DROP CONSTRAINT IF EXISTS "Product_category_fkey";

ALTER TABLE IF EXISTS "product" DROP CONSTRAINT IF EXISTS "Product_shop_fkey";

ALTER TABLE IF EXISTS "orders" DROP CONSTRAINT IF EXISTS "Orders_user_fkey";

DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "category";
DROP TABLE IF EXISTS "shop";
DROP TABLE IF EXISTS "orders";