ALTER TABLE IF EXISTS "product" DROP CONSTRAINT IF EXISTS "product_category_fkey";

ALTER TABLE IF EXISTS "product" DROP CONSTRAINT IF EXISTS "product_shop_fkey";

ALTER TABLE IF EXISTS "orders" DROP CONSTRAINT IF EXISTS "orders_user_fkey";

ALTER TABLE IF EXISTS "orders" DROP CONSTRAINT IF EXISTS "orders_user_fkey";

ALTER TABLE IF EXISTS "shop" DROP CONSTRAINT IF EXISTS "shop_owner_fkey";

DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "category";
DROP TABLE IF EXISTS "shop";
DROP TABLE IF EXISTS "orders";