// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAuthor(ctx context.Context, id int32) error
	GetUser(ctx context.Context, username string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
